### ISSUE TITLE
[FEAT] nieuw ontwerp

### ISSUE THREAD

**Issue by Swoodroom** [ThomasIAm/Swoodroom#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[swoodroom_website_1411.pdf](https://github.com/user-attachments/files/17361985/swoodroom_website_1411.pdf)

- [x] Contact modal niet lelijk

**Comment by ThomasIAm** [comment]
`<svg class="h-8 w-8 text-red-500"  width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M11 7h-5a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-5" />  <line x1="10" y1="14" x2="20" y2="4" />  <polyline points="15 4 20 4 20 9" /></svg>`

**Comment by ThomasIAm** [comment]
@Swoodroom ![Image](https://github.com/user-attachments/assets/456975aa-491c-47d0-8c2e-c8b96f50ecfe)

**Comment by ThomasIAm** [comment]
@Swoodroom https://11-feat-nieuw-ontwerp.swoodroom.pages.dev/
